# Generated by Django 3.2.6 on 2021-08-17 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rubric', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students', models.JSONField()),
                ('template', models.JSONField(default=list)),
                ('submitted_url', models.CharField(max_length=256)),
                ('group_name', models.CharField(max_length=128)),
                ('semester', models.CharField(max_length=128)),
                ('upload_time', models.DateTimeField()),
                ('export_id', models.CharField(max_length=128)),
                ('matched', models.BooleanField(default=False)),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rubric.rubric')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('html', models.TextField()),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page', to='submission.submission')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('text', models.JSONField()),
                ('sectionName', models.CharField(max_length=256)),
                ('points', models.IntegerField()),
                ('commentArray', models.JSONField()),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='submission.page')),
            ],
        ),
    ]
