# Generated by Django 3.2.6 on 2021-08-22 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='general_feedback',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
