# Generated by Django 3.2.6 on 2021-08-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.JSONField()),
                ('deadline', models.DateField()),
                ('upload_time', models.DateTimeField()),
                ('assignment_name', models.CharField(max_length=128)),
            ],
        ),
    ]
